spring:
    profiles:
        active: dev
#    main:
#        allow-bean-definition-overriding: true
logging:
        pattern:
            console: "%d %-5level %logger : %msg%n"
        level:
            org.springframework: ERROR
            com.sony.sie.loyalty.: DEBUG
            org.springframework.boot.autoconfigure: INFO
            org.springframework.orm.jpa: DEBUG
            org.springframework.transaction: DEBUG
            org.springframework.web: DEBUG
            org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

        file:
            name: /tmp/matmonkey.log
